# How to run this? -> docker-compose -f docker-compose.yaml up --abort-on-container-exit --build
version: "2"
services:
  selenium-hub:
    image: selenium/hub:3.11.0-bismuth
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.11.0-bismuth
    links:
      - selenium-hub:hub
    volumes:
      - /dev/shm:/dev/shm
      - ./downloads:/tmp/downloads
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444

  selenium-test-alpine-java:
    container_name: "issue-628"
    image: "issue-628:latest"
    build:
      context: ""
      dockerfile: Dockerfile
    depends_on:
      - chrome
    volumes:
      - ./downloads:/tmp/downloads

